// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsPetRunning():Promise<boolean>;

export function OpenPet():Promise<void>;

export function StopPet():Promise<void>;
