// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsPetRunning() {
  return window['go']['main']['SettingsApp']['IsPetRunning']();
}

export function OpenPet() {
  return window['go']['main']['SettingsApp']['OpenPet']();
}

export function StopPet() {
  return window['go']['main']['SettingsApp']['StopPet']();
}
